### ISSUE TITLE
Bundle command line tools with xde

### ISSUE THREAD

**Issue by ccheever** [exponent/xde#5]
It would be useful to be able to open a directory, open a URL in the simulator, get the URL for a project, etc. for scripting and just for development.

The command line tools should be installable the way that the atom shell commands are.

And they should roughly line up with the exp command line tools, though with a few differences.

**Comment by ccheever** [comment]
This is mostly done -- but by adding buttons to xde instead of command line tools.
I think something to open an exp:// URL would still be useful too, but I don't think this is critical for now compared to other things.

**Comment by ccheever** [comment]
there have been new requests for command line tools, both so people can script xde, and just because some people prefer it that way.

**Comment by ccheever** [comment]
there have been new requests for command line tools, both so people can script xde, and just because some people prefer it that way.

**Comment by nikki93** [comment]
I think having an XD (exponent developer) API and having XDC (exponent developer command line) and XDE (exponent developer environment) as UI layers could work well. Also for scripting, XD API could then be directly used by Javascript scripts.

**Comment by dikaiosune** [comment]
I *think* this is covered by the development of `xdl` and `exp`. Let me know if I shouldn't have closed this :).
