### ISSUE TITLE
Watchman is latest but XDE says its not

### ISSUE THREAD

**Issue by Gys** [exponent/xde#69]
I get these messages in XDE (downloaded yesterday):

```
Warning: You are using an old version of watchman (v4.5.0). This may cause problems for you.
We recommend that you either uninstall watchman (and XDE will try to use a copy it is bundled with) or upgrade watchman to a newer version, at least v4.6.0.
If you are using homebrew, try:
brew uninstall watchman; brew install watchman

```

However, I installed watchman already before installing XDE and I did it with 'brew install watchman'.
If I run 'watchman' is says "version": "4.7.0"

So something is not working correctly ?

**Comment by Gys** [comment]
An uninstall of watchman solves the problem, but that means I cannot use watchman anywhere else anymore...

**Comment by jesseruder** [comment]
What does `watchman version` say? Sometimes the watchman server is a different version than `watchman --version`.

**Comment by Gys** [comment]
`watchman version` and `watchman --version` both report 4.7.0

I decided not to use xde, instead using a more simple editor. So cannot give any further info.

**Comment by G3z** [comment]
i have the same problem
`watchman --version` `4.7.0`
`watchman -v` `4.7.0`

I also receive this message `You may need to install Xcode from https://developer.apple.com/xcode/download/.` when I try to run the code in the simulator.
I use xcode daily and the simulator is also open ATM `Version 10.0 (SimulatorApp-726.7 `

**Comment by jesseruder** [comment]
What about `watchman version` @G3z? That sometimes returns a different result.

You might need to run `sudo xcode-select -p /Applications/Xcode.app` to set the directory used by `xcrun`. If that doesn't work can you open a separate issue?

**Comment by G3z** [comment]
`watchman version` returns 4.5.0
`sudo xcode-select -s /Applications/Xcode.app` worked for the xcode issue

**Comment by G3z** [comment]
it was Deco https://github.com/decosoftware/deco-ide/issues/267
I removed it completly and the error is gone.
you can close this

**Comment by jesseruder** [comment]
Thanks for the update @G3z!
