### ISSUE TITLE
Warnings are the same color as errors

### ISSUE THREAD

**Issue by MarcusSorealheis** [exponent/xde#72]
On the project side of the XDE, some warnings are red, the same color as errors in the XDE:

jest-haste-map: @providesModule naming collision:
  Duplicate module name: core-js
  Paths: /Users/marcussorealheis/Documents/react-native-exploration/playing-with-exponent//node_modules/fbjs/node_modules/core-js/package.json collides with /Users/marcussorealheis/Documents/react-native-exploration/playing-with-exponent/node_modules/react-native/node_modules/core-js/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.

I understand the warning, but was taken aback by it being the same color as the errors. If it's worth a PR, I can open one and add it if you can't get to it. I believe it improves the XDE, though.

**Comment by jesseruder** [comment]
This actually is an error, a lot of times it'll prevent you from starting your project. It's reported back from the react native packager as an error, so we're just forwarding it.
