### ISSUE TITLE
Getting error "You may need to install Xcode..." with latest versions of Xcode and iOS simulator already installed.

### ISSUE THREAD

**Issue by Behzad-Az** [exponent/xde#78]
Running xcode Version 8.2.1 (8C1002), iOS simulator 10.0.

I open my xde project, open up simulator (e.g. iPhone 7 10.2 or iPhone 6 9.0) and click on "Open on iOS Simulator", which yields this error: "You may need to install Xcode from https://developer.apple.com/xcode/download/."

Issue #73 was similar but the root cause was that they were using an older version of xcode.

I have no issue running my project on Genymotion's Android simulator.

Any help would be highly appreciated.

**Comment by jesseruder** [comment]
Can you try running `sudo xcode-select -s /Applications/Xcode.app`? The next release will add that to the error message.

**Comment by Behzad-Az** [comment]
Awesome! thanks a lot for your help!
