### ISSUE TITLE
Being asked for password and getting "error installing xde" on every single Exponent XDE start

### ISSUE THREAD

**Issue by mostr** [exponent/xde#79]
I'm on Mac and every time I start XDE I'm being asked for password as some kind of XDE Helper wants to make some changes. I'm also presented with the error saying 
```
Error installing xde: Could not run `rm -f /usr/local/bin/xde`
```

Is this a bug? If not what I can make to supress these things? And why does it really want to do this `rm`?
![exponent_xde](https://cloud.githubusercontent.com/assets/1169259/23251315/28e60f66-f9ad-11e6-863e-d8220e67c887.png)

**Comment by jesseruder** [comment]
Sorry about that, we're working on fixing it.

**Comment by jesseruder** [comment]
Should be fixed in the latest release.

**Comment by mostr** [comment]
Works great, thanks! 👍
